// Generated by scripts/generate-template.mjs — do not edit by hand.
// Source: templates/mutual-nda.md and templates/mutual-nda-cover-page.md
// (verbatim Common Paper copies). Run `npm run generate:template` to refresh.

/**
 * The Cover Page values referenced from the Standard Terms via
 * `<span class="coverpage_link">`. Derived from the template itself, so a new
 * upstream substitution point becomes a compile error until it is handled.
 */
export type SubstitutionField = "Effective Date" | "Governing Law" | "Jurisdiction" | "MNDA Term" | "Purpose" | "Term of Confidentiality";

export type TemplateSegment =
  | { kind: "text"; value: string }
  | { kind: "strong"; value: string }
  | { kind: "link"; value: string; href: string }
  | { kind: "field"; field: SubstitutionField };

export type TemplateClause = {
  number: number;
  heading: string;
  body: readonly TemplateSegment[];
};

/**
 * The Cover Page's sections, as a union rather than `string`. Renderers switch
 * on this exhaustively, so an upstream template that adds or renames a section
 * breaks the build instead of silently rendering a blank section.
 */
export type CoverPageSectionTitle = "Purpose" | "Effective Date" | "MNDA Term" | "Term of Confidentiality" | "Governing Law & Jurisdiction" | "MNDA Modifications";

export type CoverPageSection = {
  title: CoverPageSectionTitle;
  /** Helper text from the template's `<label>`, if any. */
  hint: string;
  /** Selectable options for sections the template renders as checkboxes. */
  choices: readonly string[];
  /** Remaining prose lines, used as form placeholders. */
  body: readonly string[];
};

/** The 11 numbered clauses of the Mutual NDA Standard Terms. */
export const STANDARD_TERMS: readonly TemplateClause[] = [
  {
    "number": 1,
    "heading": "Introduction",
    "body": [
      {
        "kind": "text",
        "value": "This Mutual Non-Disclosure Agreement (which incorporates these Standard Terms and the Cover Page (defined below)) (“"
      },
      {
        "kind": "strong",
        "value": "MNDA"
      },
      {
        "kind": "text",
        "value": "”) allows each party (“"
      },
      {
        "kind": "strong",
        "value": "Disclosing Party"
      },
      {
        "kind": "text",
        "value": "”) to disclose or make available information in connection with the "
      },
      {
        "kind": "field",
        "field": "Purpose"
      },
      {
        "kind": "text",
        "value": " which (1) the Disclosing Party identifies to the receiving party (“"
      },
      {
        "kind": "strong",
        "value": "Receiving Party"
      },
      {
        "kind": "text",
        "value": "”) as “confidential”, “proprietary”, or the like or (2) should be reasonably understood as confidential or proprietary due to its nature and the circumstances of its disclosure (“"
      },
      {
        "kind": "strong",
        "value": "Confidential Information"
      },
      {
        "kind": "text",
        "value": "”). Each party’s Confidential Information also includes the existence and status of the parties’ discussions and information on the Cover Page. Confidential Information includes technical or business information, product designs or roadmaps, requirements, pricing, security and compliance documentation, technology, inventions and know-how. To use this MNDA, the parties must complete and sign a cover page incorporating these Standard Terms (“"
      },
      {
        "kind": "strong",
        "value": "Cover Page"
      },
      {
        "kind": "text",
        "value": "”). Each party is identified on the Cover Page and capitalized terms have the meanings given herein or on the Cover Page."
      }
    ]
  },
  {
    "number": 2,
    "heading": "Use and Protection of Confidential Information",
    "body": [
      {
        "kind": "text",
        "value": "The Receiving Party shall: (a) use Confidential Information solely for the "
      },
      {
        "kind": "field",
        "field": "Purpose"
      },
      {
        "kind": "text",
        "value": "; (b) not disclose Confidential Information to third parties without the Disclosing Party’s prior written approval, except that the Receiving Party may disclose Confidential Information to its employees, agents, advisors, contractors and other representatives having a reasonable need to know for the "
      },
      {
        "kind": "field",
        "field": "Purpose"
      },
      {
        "kind": "text",
        "value": ", provided these representatives are bound by confidentiality obligations no less protective of the Disclosing Party than the applicable terms in this MNDA and the Receiving Party remains responsible for their compliance with this MNDA; and (c) protect Confidential Information using at least the same protections the Receiving Party uses for its own similar information but no less than a reasonable standard of care."
      }
    ]
  },
  {
    "number": 3,
    "heading": "Exceptions",
    "body": [
      {
        "kind": "text",
        "value": "The Receiving Party’s obligations in this MNDA do not apply to information that it can demonstrate: (a) is or becomes publicly available through no fault of the Receiving Party; (b) it rightfully knew or possessed prior to receipt from the Disclosing Party without confidentiality restrictions; (c) it rightfully obtained from a third party without confidentiality restrictions; or (d) it independently developed without using or referencing the Confidential Information."
      }
    ]
  },
  {
    "number": 4,
    "heading": "Disclosures Required by Law",
    "body": [
      {
        "kind": "text",
        "value": "The Receiving Party may disclose Confidential Information to the extent required by law, regulation or regulatory authority, subpoena or court order, provided (to the extent legally permitted) it provides the Disclosing Party reasonable advance notice of the required disclosure and reasonably cooperates, at the Disclosing Party’s expense, with the Disclosing Party’s efforts to obtain confidential treatment for the Confidential Information."
      }
    ]
  },
  {
    "number": 5,
    "heading": "Term and Termination",
    "body": [
      {
        "kind": "text",
        "value": "This MNDA commences on the "
      },
      {
        "kind": "field",
        "field": "Effective Date"
      },
      {
        "kind": "text",
        "value": " and expires at the end of the "
      },
      {
        "kind": "field",
        "field": "MNDA Term"
      },
      {
        "kind": "text",
        "value": ". Either party may terminate this MNDA for any or no reason upon written notice to the other party. The Receiving Party’s obligations relating to Confidential Information will survive for the "
      },
      {
        "kind": "field",
        "field": "Term of Confidentiality"
      },
      {
        "kind": "text",
        "value": ", despite any expiration or termination of this MNDA."
      }
    ]
  },
  {
    "number": 6,
    "heading": "Return or Destruction of Confidential Information",
    "body": [
      {
        "kind": "text",
        "value": "Upon expiration or termination of this MNDA or upon the Disclosing Party’s earlier request, the Receiving Party will: (a) cease using Confidential Information; (b) promptly after the Disclosing Party’s written request, destroy all Confidential Information in the Receiving Party’s possession or control or return it to the Disclosing Party; and (c) if requested by the Disclosing Party, confirm its compliance with these obligations in writing. As an exception to subsection (b), the Receiving Party may retain Confidential Information in accordance with its standard backup or record retention policies or as required by law, but the terms of this MNDA will continue to apply to the retained Confidential Information."
      }
    ]
  },
  {
    "number": 7,
    "heading": "Proprietary Rights",
    "body": [
      {
        "kind": "text",
        "value": "The Disclosing Party retains all of its intellectual property and other rights in its Confidential Information and its disclosure to the Receiving Party grants no license under such rights."
      }
    ]
  },
  {
    "number": 8,
    "heading": "Disclaimer",
    "body": [
      {
        "kind": "text",
        "value": "ALL CONFIDENTIAL INFORMATION IS PROVIDED “AS IS”, WITH ALL FAULTS, AND WITHOUT WARRANTIES, INCLUDING THE IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE."
      }
    ]
  },
  {
    "number": 9,
    "heading": "Governing Law and Jurisdiction",
    "body": [
      {
        "kind": "text",
        "value": "This MNDA and all matters relating hereto are governed by, and construed in accordance with, the laws of the State of "
      },
      {
        "kind": "field",
        "field": "Governing Law"
      },
      {
        "kind": "text",
        "value": ", without regard to the conflict of laws provisions of such "
      },
      {
        "kind": "field",
        "field": "Governing Law"
      },
      {
        "kind": "text",
        "value": ". Any legal suit, action, or proceeding relating to this MNDA must be instituted in the federal or state courts located in "
      },
      {
        "kind": "field",
        "field": "Jurisdiction"
      },
      {
        "kind": "text",
        "value": ". Each party irrevocably submits to the exclusive jurisdiction of such "
      },
      {
        "kind": "field",
        "field": "Jurisdiction"
      },
      {
        "kind": "text",
        "value": " in any such suit, action, or proceeding."
      }
    ]
  },
  {
    "number": 10,
    "heading": "Equitable Relief",
    "body": [
      {
        "kind": "text",
        "value": "A breach of this MNDA may cause irreparable harm for which monetary damages are an insufficient remedy. Upon a breach of this MNDA, the Disclosing Party is entitled to seek appropriate equitable relief, including an injunction, in addition to its other remedies."
      }
    ]
  },
  {
    "number": 11,
    "heading": "General",
    "body": [
      {
        "kind": "text",
        "value": "Neither party has an obligation under this MNDA to disclose Confidential Information to the other or proceed with any proposed transaction. Neither party may assign this MNDA without the prior written consent of the other party, except that either party may assign this MNDA in connection with a merger, reorganization, acquisition or other transfer of all or substantially all its assets or voting securities. Any assignment in violation of this Section is null and void. This MNDA will bind and inure to the benefit of each party’s permitted successors and assigns. Waivers must be signed by the waiving party’s authorized representative and cannot be implied from conduct. If any provision of this MNDA is held unenforceable, it will be limited to the minimum extent necessary so the rest of this MNDA remains in effect. This MNDA (including the Cover Page) constitutes the entire agreement of the parties with respect to its subject matter, and supersedes all prior and contemporaneous understandings, agreements, representations, and warranties, whether written or oral, regarding such subject matter. This MNDA may only be amended, modified, waived, or supplemented by an agreement in writing signed by both parties. Notices, requests and approvals under this MNDA must be sent in writing to the email or postal addresses on the Cover Page and are deemed delivered on receipt. This MNDA may be executed in counterparts, including electronic copies, each of which is deemed an original and which together form the same agreement."
      }
    ]
  }
];

/**
 * CC BY 4.0 attribution from the Standard Terms — must accompany every document.
 * Kept as segments so the licence link survives into the output.
 */
export const STANDARD_TERMS_ATTRIBUTION: readonly TemplateSegment[] = [
  {
    "kind": "text",
    "value": "Common Paper Mutual Non-Disclosure Agreement "
  },
  {
    "kind": "link",
    "value": "Version 1.0",
    "href": "https://commonpaper.com/standards/mutual-nda/1.0/"
  },
  {
    "kind": "text",
    "value": " free to use under "
  },
  {
    "kind": "link",
    "value": "CC BY 4.0",
    "href": "https://creativecommons.org/licenses/by/4.0/"
  },
  {
    "kind": "text",
    "value": "."
  }
];

export const COVER_PAGE_TITLE = "Mutual Non-Disclosure Agreement";

export const COVER_PAGE_PREAMBLE_HEADING = "USING THIS MUTUAL NON-DISCLOSURE AGREEMENT";

/** The explanatory paragraph introducing how to use the MNDA. */
export const COVER_PAGE_PREAMBLE: readonly TemplateSegment[] = [
  {
    "kind": "text",
    "value": "This Mutual Non-Disclosure Agreement (the “MNDA”) consists of: (1) this Cover Page (“"
  },
  {
    "kind": "strong",
    "value": "Cover Page"
  },
  {
    "kind": "text",
    "value": "”) and (2) the Common Paper Mutual NDA Standard Terms Version 1.0 (“"
  },
  {
    "kind": "strong",
    "value": "Standard Terms"
  },
  {
    "kind": "text",
    "value": "”) identical to those posted at "
  },
  {
    "kind": "link",
    "value": "commonpaper.com/standards/mutual-nda/1.0",
    "href": "https://commonpaper.com/standards/mutual-nda/1.0"
  },
  {
    "kind": "text",
    "value": ". Any modifications of the Standard Terms should be made on the Cover Page, which will control over conflicts with the Standard Terms."
  }
];

/** Section titles, helper text and options as worded on the Cover Page. */
export const COVER_PAGE_SECTIONS: readonly CoverPageSection[] = [
  {
    "title": "Purpose",
    "hint": "How Confidential Information may be used",
    "choices": [],
    "body": [
      "[Evaluating whether to enter into a business relationship with the other party.]"
    ]
  },
  {
    "title": "Effective Date",
    "hint": "",
    "choices": [],
    "body": [
      "[Today’s date]"
    ]
  },
  {
    "title": "MNDA Term",
    "hint": "The length of this MNDA",
    "choices": [
      "Expires [1 year(s)] from Effective Date.",
      "Continues until terminated in accordance with the terms of the MNDA."
    ],
    "body": []
  },
  {
    "title": "Term of Confidentiality",
    "hint": "How long Confidential Information is protected",
    "choices": [
      "[1 year(s)] from Effective Date, but in the case of trade secrets until Confidential Information is no longer considered a trade secret under applicable laws.",
      "In perpetuity."
    ],
    "body": []
  },
  {
    "title": "Governing Law & Jurisdiction",
    "hint": "",
    "choices": [],
    "body": [
      "Governing Law: [Fill in state]",
      "Jurisdiction: [Fill in city or county and state, i.e. “courts located in New Castle, DE”]"
    ]
  },
  {
    "title": "MNDA Modifications",
    "hint": "",
    "choices": [],
    "body": [
      "List any modifications to the MNDA"
    ]
  }
];

export const COVER_PAGE_SIGNATURE_INTRO = "By signing this Cover Page, each party agrees to enter into this MNDA as of the Effective Date.";

/** CC BY 4.0 attribution from the Cover Page. */
export const COVER_PAGE_ATTRIBUTION: readonly TemplateSegment[] = [
  {
    "kind": "text",
    "value": "Common Paper Mutual Non-Disclosure Agreement (Version 1.0) free to use under "
  },
  {
    "kind": "link",
    "value": "CC BY 4.0",
    "href": "https://creativecommons.org/licenses/by/4.0/"
  },
  {
    "kind": "text",
    "value": "."
  }
];
